### ISSUE TITLE
求助求助

### ISSUE THREAD

**Issue by newtonysls** [SparkJiao/llama-pipeline-parallel#3]
请问有没有loss不正常的情况啊？
我改了pipeline并行后，train_batch，训练几个样本，loss直接爆炸，当我把学习率设置为0也是会变化，同时模型权重模型奇妙的也会变化，就很迷惑，但是使用eval batchloss都是处于正常范围内的

**Comment by SparkJiao** [comment]
这种情况我更倾向于是Label设置的不太对 比如你的某个sample里的label都是`ignore_index`. 可以首先尝试排除这部分的错误

**Comment by newtonysls** [comment]
我是实在找不到bug才咨询的，sample的lm
label都是看过的，是在某个step突然loss就发生巨大变化，同时在那个step模型的权重一下也突然发生很大的变化，我把学习率设置为0也是😭

**Comment by SparkJiao** [comment]
loss发生大变化不是很大的问题吧 我理解只要不是NAN就没什么问题 能正常训练 / 几步以后loss正常下降即可
可以适当增大`gradient_accumulation_steps`平滑loss

**Comment by newtonysls** [comment]
从一点几突然变为10点几，还不大么🙋，就好离谱

**Comment by SparkJiao** [comment]
10+的loss很常见 可能只是你的数据问题

**Comment by newtonysls** [comment]
了解，感谢哈，我已经放弃用pipeline了，增大sequence length换一下其他方法

**Comment by xinpeng-zhang** [comment]
可以加个好友，和大佬们一起探讨下嘛，我的pp也有很大问题

**Comment by newtonysls** [comment]
我已经放弃使用llama的pipeline了 hh
没找出原因，llama的tokenizer对中文很不友好，后面换了基座模型了，节省显存也可以使用gradient
ckpt，直接在llama源码里设置为true就好

**Comment by xinpeng-zhang** [comment]
我是在调chatglm2的pp，loss开始是10左右，然后训练几百step降到0.1。loss虽然在降，但是推理崩了，一直在重复同一个token

**Comment by newtonysls** [comment]
我的训练和你一样，前几个样本loss正常，后面直接增到10几，而且我发现在没达到梯度更新的时候模型权重就变化了，所以我也没找到原因，推理出来的结果也很怪异

**Comment by realgump** [comment]
感觉可能是通信的问题：
https://github.com/microsoft/DeepSpeed/issues/4726
