### ISSUE TITLE
pipeline with zero1, does not optimize gpu meomery

### ISSUE THREAD

**Issue by xinpeng-zhang** [SparkJiao/llama-pipeline-parallel#4]
when I set zero to stage 0, the gpu memory is similar with setting zero to stage 1

**Comment by SparkJiao** [comment]
To my understanding, pure pipeline parallelism has already include partition mechanism like zero-2, where the optimizer in each stage only control the updates of its own partition.

If you want further optimization, it would be observed when you enable hybrid parallel, e.g., 8 GPU with 4-route pipeline parallel and 2-route data parallel.

**Comment by xinpeng-zhang** [comment]
> 

yes, i have done that. And i find 4 PP * 2 DP is same as 8 PP * 1 DP. Is there any chance that I have you on wechat: bestzxp

**Comment by SparkJiao** [comment]
Maybe you can check if you have enabled cpu offload.
